# Generated by Django 3.1 on 2020-09-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200913_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='post',
            name='github',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='yt_eng',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name='Difficulty',
        ),
    ]
